permissions:
  contents: write

name: Deploy React App to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Docker on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Notify Deployment Started to Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Deployment to Docker has started for React App."}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Pull Docker image
        run: docker pull dheepans/sample-react-app:latest

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 dheepans/sample-react-app:latest

      - name: Wait for Container to Start
        run: sleep 30  # Optional, adjust based on app startup time

      - name: Notify Deployment Success to Google Chat
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Deployment to Docker completed successfully for React App!"}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

      - name: Notify Deployment Failure to Google Chat
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Deployment to Docker failed for React App."}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
