name: Deploy React App to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:  
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Start

        run: |

          cd /home/dheepan-s/builder/notify

          bash started.sh "$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')" "Development"  "${{ github.ref_name }}" "${{ github.event.pusher.name }}" "${{ github.event.head_commit.message }}" "${{ github.repository }}"

      - name: Install dependencies
        run: |
         cd /home/dheepan-s/sample-react-gapp
         git stash
         git fetch
         git checkout "${{ github.ref_name }}"
         git pull
         docker rm -f dheepan_react
         docker build -t dheepan_react .
         docker run -itd --name dheepan_react_container -p 3000:80 dheepan_react

      - name: Notify Success

        if: success()

        run: |

          cd /home/dheepan-s/builder/notify

          bash complete.sh "$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')" "Development" "${{ github.ref_name }}" "${{ github.event.pusher.name }}" "${{ github.event.head_commit.message }}" "${{ github.repository }}" "${{ github.run_started }}" "${{ github.run_id }}"



      - name: Notify Failure

        if: failure()

        run: |

          cd /home/dheepan-s/builder/notify

          bash failed.sh "$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')" "Development" "${{ github.ref_name }}" "${{ github.event.pusher.name }}" "${{ github.event.head_commit.message }}" "${{ github.repository }}"
